version: '3'

services:
    mysql:
        container_name: mars_rover_mission_mysql
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - "3336:3306"
        volumes:
            - "./resources/docker/local/mysql/data:/var/lib/mysql"
            - "./resources/docker/local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "./resources/docker/local/mysql/sql:/docker-entrypoint-initdb.d"
        tmpfs:
            - /var/lib/mysql/:rw,noexec,nosuid,size=600m
            - /tmp/:rw,noexec,nosuid,size=50m
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=mars_rover_mission

    nginx:
        container_name: mars_rover_mission_nginx
        image: nginx:1.15-alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ".:/var/www:cached"
            - "./resources/docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
        depends_on:
            - php

    php:
        container_name: mars_rover_mission_php
        build:
            context: .
            dockerfile: resources/docker/local/php-fpm/Dockerfile
        restart: unless-stopped
        volumes:
            - ".:/var/www:cached"
        env_file:
            - .env
        depends_on:
            - mysql
